name: build-windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app (PyInstaller ONEDIR)
        shell: cmd
        run: |
          pyinstaller --noconfirm --clean --noconsole --onedir ^
            --name "PaladiumDesktop" ^
            --hidden-import=pkgutil ^
            --collect-all PyQt6 ^
            --collect-all PyQt6.QtCore ^
            --collect-all PyQt6.QtGui ^
            --collect-all PyQt6.QtWidgets ^
            --collect-all PyQt6.QtCharts ^
            paladium_desktop.py

      - name: Install Inno Setup (Chocolatey)
        run: choco install innosetup --yes --no-progress

      - name: Build Installer (Inno Setup)
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer.iss"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PaladiumDesktop-windows
          path: |
            dist\PaladiumDesktop\**
            Output\*.exe
